@startuml
!include style.puml
title Undo Sequence Diagram for Add Exercise

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":UndoCommand" as UndoCommand LOGIC_COLOR
participant ":EventHistory" as EventHistory LOGIC_COLOR
participant ":Event" as Event LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

    LogicManager -> AddressBookParser : parseCommand("undo")
    activate AddressBookParser

        create UndoCommand
        AddressBookParser -> UndoCommand
        activate UndoCommand

        UndoCommand --> AddressBookParser
        deactivate UndoCommand

    AddressBookParser --> LogicManager : command
    deactivate AddressBookParser

    LogicManager -> UndoCommand : execute(model)
    activate UndoCommand

        UndoCommand -> EventHistory : undo(model)
        activate EventHistory

            EventHistory -> Event : undo(model)
            activate Event

                Event -> Model : deleteExercise(exercise)
                activate Model

                Event -[hidden]-> Model

                Model --> Event
                deactivate Model


            Event --> EventHistory
            deactivate Event

        EventHistory --> UndoCommand : eventToUndo
        deactivate EventHistory

    UndoCommand --> LogicManager : commandResult
    deactivate UndoCommand

    UndoCommand -[hidden]-> LogicManager : commandResult
    destroy UndoCommand

[<--LogicManager : commandResult
deactivate LogicManager
@enduml
